package com.yuudati.bookmanager.entity;

public class BookCharacters {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_characters.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_characters.book_id
     *
     * @mbg.generated
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_characters.character
     *
     * @mbg.generated
     */
    private String character;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_characters
     *
     * @mbg.generated
     */
    public BookCharacters(Integer id, String bookId, String character) {
        this.id = id;
        this.bookId = bookId;
        this.character = character;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_characters
     *
     * @mbg.generated
     */
    public BookCharacters() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_characters.id
     *
     * @return the value of book_characters.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_characters.id
     *
     * @param id the value for book_characters.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_characters.book_id
     *
     * @return the value of book_characters.book_id
     *
     * @mbg.generated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_characters.book_id
     *
     * @param bookId the value for book_characters.book_id
     *
     * @mbg.generated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_characters.character
     *
     * @return the value of book_characters.character
     *
     * @mbg.generated
     */
    public String getCharacter() {
        return character;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_characters.character
     *
     * @param character the value for book_characters.character
     *
     * @mbg.generated
     */
    public void setCharacter(String character) {
        this.character = character == null ? null : character.trim();
    }
}