package com.yuudati.bookmanager.entity;

public class BookAttributes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_attributes.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_attributes.book_id
     *
     * @mbg.generated
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_attributes.attribute
     *
     * @mbg.generated
     */
    private String attribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_attributes
     *
     * @mbg.generated
     */
    public BookAttributes(Integer id, String bookId, String attribute) {
        this.id = id;
        this.bookId = bookId;
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_attributes
     *
     * @mbg.generated
     */
    public BookAttributes() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_attributes.id
     *
     * @return the value of book_attributes.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_attributes.id
     *
     * @param id the value for book_attributes.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_attributes.book_id
     *
     * @return the value of book_attributes.book_id
     *
     * @mbg.generated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_attributes.book_id
     *
     * @param bookId the value for book_attributes.book_id
     *
     * @mbg.generated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_attributes.attribute
     *
     * @return the value of book_attributes.attribute
     *
     * @mbg.generated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_attributes.attribute
     *
     * @param attribute the value for book_attributes.attribute
     *
     * @mbg.generated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }
}